import {
    FaAws,
    FaBug,
    FaDocker,
    FaGithub,
    FaLock,
    FaMicrosoft,
    FaPython,
    FaSearch,
    FaShieldAlt
} from "react-icons/fa";
import {
    SiAnsible,
    SiElasticstack,
    SiGitlab,
    SiGooglecloud,
    SiGrafana,
    SiJenkins,
    SiKubernetes,
    SiPrometheus,
    SiTerraform,
} from "react-icons/si";

const ExperienceData = [
    {
        id: 1,
        icon: FaAws,
        color: "#FF9900",
        target: "_blank",
        category: "devops",
        name: "AWS",
    },
    {
        id: 2,
        icon: FaMicrosoft,
        color: "#0078D4",
        target: "_blank",
        category: "devops",
        name: "Azure",
    },
    {
        id: 3,
        icon: SiGooglecloud,
        color: "#4285F4",
        target: "_blank",
        category: "devops",
        name: "GCP",
    },
    {
        id: 4,
        icon: FaDocker,
        color: "#2496ED",
        target: "_blank",
        category: "devops",
        name: "Docker",
    },
    {
        id: 5,
        icon: SiKubernetes,
        color: "#326CE5",
        target: "_blank",
        category: "devops",
        name: "Kubernetes",
    },
    {
        id: 6,
        icon: SiTerraform,
        color: "#7B42BC",
        target: "_blank",
        category: "devops",
        name: "Terraform",
    },
    {
        id: 7,
        icon: SiJenkins,
        color: "#D24939",
        target: "_blank",
        category: "devops",
        name: "Jenkins",
    },
    {
        id: 8,
        icon: SiAnsible,
        color: "#EE0000",
        target: "_blank",
        category: "devops",
        name: "Ansible",
    },
    {
        id: 9,
        icon: FaGithub,
        color: "#181717",
        target: "_blank",
        category: "devops",
        name: "GitHub Actions",
    },
    {
        id: 10,
        icon: SiGitlab,
        color: "#FC6D26",
        target: "_blank",
        category: "devops",
        name: "GitLab CI",
    },
    {
        id: 11,
        icon: FaAws,
        color: "#FF9900",
        target: "_blank",
        category: "devops",
        name: "AWS CodePipeline",
    },
    {
        id: 12,
        icon: SiGooglecloud,
        color: "#4285F4",
        target: "_blank",
        category: "devops",
        name: "Google Cloud Build",
    },

    {
        id: 13,
        icon: FaShieldAlt,
        color: "#258FB8",
        target: "_blank",
        category: "cybersecurity",
        name: "Metasploit",
    },
    {
        id: 14,
        icon: FaShieldAlt,
        color: "#1679A7",
        target: "_blank",
        category: "cybersecurity",
        name: "Wireshark",
    },
    {
        id: 15,
        icon: FaSearch,
        color: "#00A800",
        target: "_blank",
        category: "cybersecurity",
        name: "Nessus",
    },
    {
        id: 16,
        icon: FaBug,
        color: "#FF6633",
        target: "_blank",
        category: "cybersecurity",
        name: "Burp Suite",
    },
    {
        id: 17,
        icon: FaLock,
        color: "#003366",
        target: "_blank",
        category: "cybersecurity",
        name: "Acunetix",
    },

    {
        id: 18,
        icon: FaPython,
        color: "#306998",
        target: "_blank",
        category: "programming",
        name: "Python",
    },
    {
        id: 19,
        icon: FaMicrosoft,
        color: "#4EAA25",
        target: "_blank",
        category: "programming",
        name: "Bash",
    },
    {
        id: 20,
        icon: FaMicrosoft,
        color: "#4EAA25",
        target: "_blank",
        category: "programming",
        name: "Shell Scripting",
    },

    {
        id: 21,
        icon: SiElasticstack,
        color: "#005571",
        target: "_blank",
        category: "monitoring",
        name: "ELK Stack",
    },
    {
        id: 22,
        icon: SiPrometheus,
        color: "#E6522C",
        target: "_blank",
        category: "monitoring",
        name: "Prometheus",
    },
    {
        id: 23,
        icon: SiGrafana,
        color: "#F46800",
        target: "_blank",
        category: "monitoring",
        name: "Grafana",
    },

    {
        id: 24,
        icon: FaAws,
        color: "#FF9900",
        target: "_blank",
        category: "orchestration",
        name: "Amazon EKS",
    },
    {
        id: 25,
        icon: SiGooglecloud,
        color: "#4285F4",
        target: "_blank",
        category: "orchestration",
        name: "GKE",
    },
    {
        id: 26,
        icon: FaMicrosoft,
        color: "#0078D4",
        target: "_blank",
        category: "orchestration",
        name: "AKS",
    },
];

export default ExperienceData;